### ISSUE TITLE
Roadmap for dev-sec web assets

### ISSUE THREAD

**Issue by chris-rock** [dev-sec/dev-sec.github.io#17]
At this point, we have three different repositories to main our web assets:

- https://github.com/dev-sec/dev-sec.github.io
- https://github.com/dev-sec/blog
- https://github.com/dev-sec/docs

This is very confusing to our users and does not encourage our community to update the content regularly. In addition, the project has extended its scope dramatically over the last year. We have a lot new profiles available that are not discoverable via the website. Those are only *visible* if your familiar with Github. Therefore, I am proposing the following steps:

Step 1: *Migrate*
- migrate all content as is to hugo in a single repository
- do not apply style changes to simplify the migration

Step 2: *update content*
- harmonize content
- page to discover all individual github projects
- leaderbaord to display top contributors similar to https://github.com/ejholmes/leaderboard

Step 3: *discoverability of profiles*
- turn home page in a profile-centric view similar to https://www.stigviewer.com/stig/windows_server_2016/
- align all hardening modules (ansible, chef, puppet) to a profile

**Comment by rndmh3ro** [comment]
Looks good to me!

Step 1 should be the most important one so (as you said) others can more easily contribute!

BTW: It's the first time I saw http://dev-sec.io/docs/. Looking at the content I don't know if all the content is actually needed there. I actually like the content in the introduction, so this should stay (and be harmonized with the homepage).

> page to discover all individual github projects

I don't know if this is actually needed if we got the supermarket, forge, galaxy, and so on. Maybe some curated links to these with descriptions would be enough? Supermarket, forge etc. will probably be most relevant in finding our projects.

> turn home page in a profile-centric view similar to https://www.stigviewer.com/stig/windows_server_2016/

You mean inspec-profiles?

**Comment by chris-rock** [comment]
I think you're right @rndmh3ro In my hugo branch, I moved most of the docs content into other sections, the chef/puppet descriptions is more up-to-date in their appropriate repositories, therefore it can be deleted from the webpage. The current working version (a lot of styling is still missing) is available here https://bricklayer-mole-54424.netlify.com/

Regarding the profiles: Yes, especially if your're not into InSpec's code, its not so easy to discover what controls are included and what our profiles as well as our hardening modules are covering. It would be nice to see that more visually.

**Comment by mattray** [comment]
I'm not very familiar with Hugo, but anything making the content more accessible is welcome in my opinion and I'm happy to assist with the refactoring given I want to push a bunch of government and banks this way.

Given that some of the content is a little bit dated, I'd actually like see it pared down a bit so it's more like a GitHub page for the project. I think the Articles and Blogs can be collapsed into 1 link ("News"?) and try to get more cross-posting into that. The links under Chef, Puppet & Ansible could probably be removed and replaced by making the text above links to the GitHub projects. For Community I didn't even know about the Gitter group. Do we want to point people to https://www.inspec.io/community/ as well? I'd like to create #dev-sec in the Chef Community Slack since #inspec is already there.

Perhaps 2 main sections:

**Compliance as Code**
   - aligned around InSpec
   - implementing existing standards and establishing open source baselines
   - links to GitHub pages

**Infrastructure Hardening as Code**
   - Operating systems and applications
   - Chef, Puppet & Ansible
   - links to GitHub pages

The content in Docs is probably a bit stale too, parts could be on the main page (Introduction, links to Chef & Puppet modules) and possibly broken out (Coding moved to Community).

**Comment by chris-rock** [comment]
@mattray I already clean up some content and the docs section is essentially non-existent anymore since those are better covered in their appropriate repositories (as you pointed out).

I like your idea about the news, where we blend in internal and external content under one section. Its a bit more difficult to achieve, so we can tackle that once the first hugo iteration is out. Maybe you can have a look how we could achieve that?

From my perspective, the main goal of dev-sec is to define security benchmarks and to provide applicable tooling. At this point, benchmarks are defined in InSpec and remediated with Ansible, Chef or Puppet. Therefore I would love to find a way where we are talking about a baselines without spliting the perspectives too much. I think, views similar to the stig viewer would be very helpful.

Therefore I am very hesitant to point everybody to the InSpec community, I see some overlap, but the InSpec community deals mainly with technical issues around inspec code, not the contents of the  benchmarks itself. The dev-sec community is a vendor-neutral community that tries to focus on the best applicable implementation from the security perspective.

**Comment by artem-sidorenko** [comment]
@chris-rock I like it! Thanks for working on the improvement in this area!

> I think the Articles and Blogs can be collapsed into 1 link ("News"?) and try to get more cross-posting into that.

I like the idea too

> I like your idea about the news, where we blend in internal and external content under one section. Its a bit more difficult to achieve, so we can tackle that once the first hugo iteration is out. Maybe you can have a look how we could achieve that?

Why not converting articles to the blog posts? You could cross-post the content and embed videos in the posts. But we can improve it later too.

I'm a bit confused about Baseline section on top, as insider I might get the message behind, but as new visitor? Not sure. As we have an overview over implementations on the main page, why not to include the baselines on the main page too (maybe we should consider using another overview here)

The bottom navigation pane isn't prominent as well, I would avoid it either at all or just keep the link to the legal notice there. 'About' belongs in my eyes to the top nav-pane, I usually expect the 'about' page to be easy&fast to find. Links to twitter/gitter could be placed within About/Community sections. I also would set links to the ansible galaxy/supermarket/puppet forge as link on the main page

Regarding 'imprint': https://false-friends.crellin.de/2009/10/please-stop-using-word-imprint-for.html

just my 2cent:)

**Comment by chris-rock** [comment]
After thinking about it, I think the News section is a great idea. We may not be there with the first iteration, but I try my best.

@artem-sidorenko I also agree that we need to play with the content and that the iteration is not the last one. I am also thinking we need a getting started for ansible, chef, puppet and inspec user. By clicking on the logos, we could directly guide to that.

Agree project should be in the top bar.

For imprint i was only following document foundation https://www.libreoffice.org/imprint

**Comment by chris-rock** [comment]
@artem-sidorenko I added the baselines to the front page

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1178413/46875631-7751a880-ce3c-11e8-869e-a7dbb43e33da.png">

**Comment by rndmh3ro** [comment]
@chris-rock For me its not clear that in the overview picture the Compoments are actually clickable links. I think this should stand out more, maybe with adding a "link-image" or something..?

**Comment by artem-sidorenko** [comment]
@chris-rock I clicked on the baseline and got the reason behind the new github repo of @arlimus, very cool :D

**Comment by chris-rock** [comment]
Haha, yeah. Please do not expect from me that everything will be perfect. I am trying to wrap up the first iteration and we can split up to get the page into the shape we want going forward.

**Comment by chris-rock** [comment]
I merged articles and blogs under a news section:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1178413/46903133-1627e480-ced1-11e8-9753-a46e3526cf52.png">

Therefore we can easily link new external blog post in our news section going forward.

**Comment by chris-rock** [comment]
🎉 I think I got the website into a usable solution. Far away from perfect, but I think its cleaner and better than before. https://bricklayer-mole-54424.netlify.com/index.html

If you find major bugs, I am happy to fix them before releasing the page, otherwise lets track the issues as separate issues so that we can all work together to make the page better.

This version has already a simple version of the contributor leaderboard, a profile viewer and is merging all the assets main page, blog and docs together. Once released, I am going to archive docs and blog repo.

**Comment by artem-sidorenko** [comment]
@chris-rock many thanks, good work! Really appreciated!
