### ISSUE TITLE
rss for blog

### ISSUE THREAD

**Issue by elisdg** [dev-sec/dev-sec.github.io#59]
Hi,
is it possible to provide an rss feed for the blog?
I tried to do it through github, but for the website there are no releases (otherwise I could use https://github.com/dev-sec/dev-sec.github.io/releases.atom).
Or is there another way?
BR

**Comment by rndmh3ro** [comment]
The RSS can be found here: https://dev-sec.io/blog/index.xml

We should add this to the blog itself.

**Comment by elisdg** [comment]
I didn't find that url, thank you. 
that would be cool, yes

**Comment by rndmh3ro** [comment]
I'm keeping this open as a reminder to add the rss-link to the blog.
