### ISSUE TITLE
Use netlify.com instead of github pages

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/dev-sec.github.io#9]
I've created a test setup with hugo and autodeployment via travis to my shared space on Hetzner:

 - https://dev-sec.sidorenko.io/
 - https://github.com/artem-sidorenko/test-dev-sec
 - https://travis-ci.org/artem-sidorenko/test-dev-sec
 - https://www.ssllabs.com/ssltest/analyze.html?d=dev-sec.sidorenko.io&hideResults=on

It has SSL certificate from Symantec (provided on the Hetzner hosting free of charge) and has A-Rating of ssl test.

A possible alternative might be netlify (used by hugo itself), its free for opensource and promises free SSL and CDN:
 - https://www.netlify.com
 - https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/

How do we want to proceed? Is Hetzner-setup good enough for us?

**Comment by chris-rock** [comment]
In our discussion, we decided to improve our website assets by:
- migrate landing page, docs and blog into one repository
- use hugo to manage the content
- use netlify.com to host the content

**Comment by chris-rock** [comment]
Github is supporting https now. Therefore we do not need to move. Thank you @artem-sidorenko for the recommenndation
